#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

# prevent creating pycache in repo area
import sys
wrtSave = sys.dont_write_bytecode
sys.dont_write_bytecode = True

import os
Import('env')

Import('mu2e_helper')
helper = mu2e_helper(env)

# this python code generates Trigger fcl in gen/
import generateMenuFromJSON

sys.dont_write_bytecode = wrtSave

# run like this, it just generates the source and target file listss
menus      = ["physMenu","extrPosMenu", "valMenu"]
evtModes   = ["OnSpill","OffSpill","all"]
for m in menus:
    for evt in evtModes:
        muse_w_dir = os.environ['MUSE_WORK_DIR']
        muse_b_dir = os.environ['MUSE_BUILD_DIR']
        menu_file  = muse_w_dir+'/mu2e_trig_config/data/{}.json'.format(m)
        out_dir    = muse_b_dir+'/mu2e_trig_config'
        sources, targets, command = generateMenuFromJSON.generateOffline(menu_file, 
                                                                         evt,
                                                                         out_dir,
                                                                         False,
                                                                         False )
        # this schedules it to run again to make the files
        helper.make_generic(sources,targets,command+" -mf {} -o {}/gen -evtMode {}".format(menu_file, out_dir, evt))


# this tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
